sudo: required
services:
  - docker

before_install:
  - docker build -t irinaid/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run irinaid/react-test npm run test -- --coverage
  
after_success:
  - docker built -t irinaid/multi-client ./client
  - docker built -t irinaid/multi-nginx ./nginx 
  - docker built -t irinaid/multi-server ./server
  - docker built -t irinaid/multi-worker ./worker  

# Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take those images and oush them to docker hub
 - docker push irinaid/multi-client
 - docker push irinaid/multi-nginx
 - docker push irinaid/multi-server
 - docker push irinaid/multi-worker 